#@server = https://maryoriesp-musical-yodel-qwgggv9xwrxh94pg-8080.preview.app.github.dev
@server = https://semana8.onrender.com
@apiserver = {{server}}/api/curso
###

GET {{server}}/
###
GET {{server}}/codigo
###
GET {{server}}/nombre-completo
###
GET {{apiserver}}/listar
###
POST {{apiserver}}/nuevo
Content-Type: application/x-www-form-urlencoded

nombre=Algoritmos&creditos=3
###
DELETE {{apiserver}}/eliminar
Content-Type: application/x-www-form-urlencoded

id=1